connections:
  - name: mongodb1
    type: MONGO
    connectionStringFromEnv: MONGO_CONN
    metrics:
      - name: active_user_count
        helpString: users in the product
        database: yolo_db
        collection: user
        query: '{"is_active":true}'
        time: 60
      - name: total_user_count
        helpString: users in the product
        database: yolo_db
        collection: user
        query: ""
        time: 120
  - name: postgres1
    type: SQL
    connectionStringFromEnv: POSTGRES_CONN
    metrics:
      - name: template_count
        helpString: products in the db
        query: select * from templates
        time: 10
